### ISSUE TITLE
Generate figures for publication directly from pyCapsid

### ISSUE THREAD

**Issue by luque82** [luquelab/pyCapsid#2]
+ When executing pyCapsid, it would be ideal that the package generates the capsid and the protein (mapped to results) for the user (in png format, for example).
+ Additionally, the script to generate those figures in ChimeraX would be a possible compromise.

**Comment by colintravisbrown** [comment]
How to include the python script with the installation?

**Comment by luque82** [comment]
This original issue was resolved. The current development is taking care of improving the quality standard for the figures to facilitate users to reuse pyCapsid outputs in their publications. Any issues regarding these improvements will be opened separately.
