### ISSUE TITLE
Colab: Include output with dynamics

### ISSUE THREAD

**Issue by luque82** [luquelab/pyCapsid#26]
It is important to include results regarding the dynamics. Ideally, this should include:
+ Display a movie with the fluctuations of the capsid for the optimal number of modes selected in the notebook (like the one you shared in your thesis).
+ Save the movie as an output result.
+ Include an output file with information to generate the dynamics (e.g., periodic trajectory of coordinates over time or a recipe/script to generate the coordinates and movies given the optimal number of modes selected.

**Comment by luque82** [comment]
Colin, include one (or a few) cell(s) generating the snapshots for the gif and including the python library and code to render the gif by the user uploading the files.

**Comment by colintravisbrown** [comment]
This can now be done using a ChimeraX command
