### ISSUE TITLE
Colab: Add arrays to bfactors.npz

### ISSUE THREAD

**Issue by luque82** [luquelab/pyCapsid#29]
The added file `bfactors.npz` was a significant improvement. This is issue points out the modifications necessary to complete this part:
+ Include an array, e.g., `bfactors_experimental`, for the experimental values.
+ Include an array, e.g, `residue_number`, with the residue number (instead of relying on the index).
     + The counts of elements in a PDB starts at one, and this is also the common counting start for folks outside software development environments like python or C.
+ Include a value, e.g., `asym_unit_residues`, with the number of residues in the asymmetric unit.
     + This will reduce the barrier for developers and the user to quickly explore plots for either the full structure or asymmetric unit.
+ Change the name of the file `b_factors.svg` to `bfactors.svg` to match the npz file (or the other way around).
     + Names must help make the outputs intuitive. Variations in names or formats can be confusing for the user and reduce confidence.

**Comment by colintravisbrown** [comment]
Done. See contents of previous commit for details.
