### ISSUE TITLE
Colab: Optimal number of modes (B-factors fit)

### ISSUE THREAD

**Issue by luque82** [luquelab/pyCapsid#31]
The current notebook does not seem to store the optimal number of modes obtained in the B-factor fitting either on a variable or file. This is a key results that needs to be easy to access. Include it ideally as an accessible variable in the Colab as well as within some of the output files.

In the `Interpret results` section I used a temporary solution using the length of the array `evals_scaled`, but we need a more robust solution.

After investigateing the code, my understanding is that the function `fitBfactors` returns a variable n_m that I interpret is the ideal number of modes. However, this function is not loaded explicitly in the Colab. Maybe using this function could offer a simple and not computationally expensive way to address the issue. But you'll probably have a better idea.

**Comment by colintravisbrown** [comment]
Resolved. The number of modes is now returned in fitCompareBfactors.
