### ISSUE TITLE
Colab: The notebook sometimes requires access to third-party Jupyter widgets

### ISSUE THREAD

**Issue by luque82** [luquelab/pyCapsid#34]
It is unclear if the following issue can cause an error on users. In any case, it should be addressed to avoid confusing and impact the user's trust on the tool.

Message received on the side pane:
Code snippets

Text:
Support for third party widgets (widgets outside of the ipywidgets package) needs to be enabled separately. Support for these widgets will be loaded from a CDN external from Colab.

Code:
from google.colab import output
output.enable_custom_widget_manager()

Text:
Support for third party widgets will remain active for the duration of the session. To disable support:
from google.colab import output
output.disable_custom_widget_manager()

**Comment by colintravisbrown** [comment]
This is warning us that we need to run that first block of code to use NGLView. That code block is already included in the same cell in which we install pyCapsid using pip. However, Colab continues to issue the warning whenever NGLView is used.
