### ISSUE TITLE
Colab: Error in the `Generate advanced analysis` section

### ISSUE THREAD

**Issue by luque82** [luquelab/pyCapsid#41]
There seems to be an incompatibility when unpacking getCapsid(pdb) (see error message below).

# Error message:
Visualizing cluster results of 4oq8 for 20 clusters
[15 15 15 ...  9  9  9]
No capsid structure provided, getting capsid.
Fetching file 1 / 1 (4oq8)...
Done
Number of protein chains in full structure: 60
Number of protein chains in asymmetric unit: 1
# of residues: 8640
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-34-00321f92f4cd>](https://localhost:8080/#) in <cell line: 3>()
      1 from pyCapsid.VIS import visualizeSavedResults
      2 results_file = f'{pdb}_final_results_full.npz' # Path of the saved results
----> 3 labels_20, view_clusters = visualizeSavedResults(pdb, results_file, n_cluster=20, method='nglview')
      4 view_clusters

1 frames
[/usr/local/lib/python3.10/dist-packages/pyCapsid/VIS.py](https://localhost:8080/#) in createCapsidView(pdb, capsid)
    339         print('No capsid structure provided, getting capsid.')
    340         from pyCapsid.PDB import getCapsid
--> 341         capsid, _, _, _, _, _ = getCapsid(pdb)
    342 
    343     import biotite.structure.io as strucio

ValueError: too many values to unpack (expected 6)

**Comment by colintravisbrown** [comment]
The most recent release of pyCapsid addresses this issue.

**Comment by colintravisbrown** [comment]
Tested, this is fixed
