### ISSUE TITLE
pyCapsid/Colab: Why residue 1 is so large experimentally compare to the rest?

### ISSUE THREAD

**Issue by luque82** [luquelab/pyCapsid#43]
Is there any issue reading the B-factors from the PDB or internally?

I've noticed that the first residue has a much larger B-factor experimental value than the rest of experimental B-factors and that the predicted value.

**Comment by colintravisbrown** [comment]
![image](https://github.com/luquelab/pyCapsid/assets/54756825/5d347bd6-1b26-40c0-80f6-6d9224c59536)
Checking in ChimeraX. The b-factor value is correct. It seems to be a very mobile residue.

**Comment by luque82** [comment]
That sounds right. That terminal domain seems an intrinsically disordered protein (IDP) domain. It seems to adopt a configuration only in the capsid, but it makes sense that it is very flexible. It is a very common situation in protein complexes,  don't know why I didn't think about it (my postdoc was about these type of protein structures in chromatin). Good catch.

This is a great insight, and a great way to identify the regions were we need more refined methods to capture flexibility of proteins in capsids.
