### ISSUE TITLE
pyCapsid (Colab): Make accessible the results in `coeffs` (correlation coefficients)

### ISSUE THREAD

**Issue by luque82** [luquelab/pyCapsid#44]
The correlation coefficients for the different modes are stored in the variable `coeffs` obtained in the function `fitBfactors` within the object `bfactorfit.py`. The plot of CC vs modes is generated within fitBfactors (relying on other functions). However, these values remain obscure within the execution of the package. 

The user must have access to these key values.

**Comment by colintravisbrown** [comment]
Results are now saved in the same manner as others. See the above commit for details.

**Comment by luque82** [comment]
This works now :).
