### ISSUE TITLE
pyCapsid (Colab): Replace usage of os.chdir() with paths specifying the full target directory

### ISSUE THREAD

**Issue by colintravisbrown** [luquelab/pyCapsid#45]
Usage of os.chdir() across different cells causes errors if execution is ever interrupted or when using asynchronous saving which is necessary for writing local images using NGLView.

**Comment by luque82** [comment]
Got it. I agree that using os.chdir() is not the safest move in any case.

I'll specify the path in matplotlib when saving figures and pandas when saving the csv files. That should resolve the issue.
