### ISSUE TITLE
Colab: Add warning message in the quick-start guide about third-party widgets

### ISSUE THREAD

**Issue by luque82** [luquelab/pyCapsid#46]
Warn the user regarding the possibility of the code snippet popping up mentioning instructions for third-party Jupyter widgets.

Point out to the reader that unless they have an unusual configurations, they can disregard the comment.

**Comment by colintravisbrown** [comment]
I added a warning for this in the comments of the relevant cell. Since NGLView is no longer the default, a small warning l like that should be enough.
