### ISSUE TITLE
Colab: ChimeraX errors following readme file

### ISSUE THREAD

**Issue by luque82** [luquelab/pyCapsid#51]
Here are the two current issues when following the instructions from the readme file:

1. The file asks the user to `run the following command`:
    + `runscript "path/to/pyCapsid_report/chimerax/chimerax_script.py" "path/to/pyCapsid_report/chimerax/`
    + However, most users won't understand how they have to change the path
     + I suggest to change slightly the instructions. Instead of `run the following command` say `follow these instructions`
     + Add a step indicating the user to copy the path for pyCapsid_report and include an example, e.g., `/Users/aluque/Downloads/pyCapsid_report`
     + Add a step indicating the In the `runscript` line, the copied path must replace the portion "/path/to/pycapsid_report". Include example, e.g., for each portion of the command, e.g., `/Users/aluque/Downloads/pyCapsid_report/chimerax/chimerax_script.py` and `/Users/aluque/Downloads/pyCapsid_report/chimerax/chimerax_script.py/4oq8_cluster_colors.npy`

2. When I replaced the path for my local files and run the script in chimeraX, I received the following error:
```
Traceback (most recent call last):
File "/Users/aluque/Downloads/pyCapsid_report/chimerax/chimerax_script.py", line 79, in 
color_dir, save_dir, pdb_dir, remote, pdb, rwb_scale = (sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5], sys.argv[6])
IndexError: list index out of range
```
 It looks like the sys.argv values where not replaced correctly. Ideally, we should avoid the user having to do any changes in the script, but if that is necessary, the instructions should be explicit in the readme file.

**Comment by colintravisbrown** [comment]
This works on my end. Can you share a screenshot of what command you ran? It sounds like ChimeraX is missing one of the other arguments (which are not optional, this is something that will be refactored later), or it didn't parse them correctly. This is what the full command looks like for me.

![image](https://github.com/luquelab/pyCapsid/assets/54756825/508e267d-7194-45f8-9f73-8179eac93dbd)

**Comment by colintravisbrown** [comment]
The command used to run the ChimeraX script has been simplified significantly
