### ISSUE TITLE
Colab: Mention the ChimeraX portion in the Quick-start guide

### ISSUE THREAD

**Issue by luque82** [luquelab/pyCapsid#52]
Add a bullet point in the Quick-start guide navigating the user to what to do with ChimeraX and the benefits of it. Include a cross-reference to a Colab section for further details if necessary.

**Comment by colintravisbrown** [comment]
I added an explanation to the quick-start guide. Still need a description of ChimeraX

**Comment by luque82** [comment]
The main problem motivating this Issue #52 has been addressed.

Separate issues might be generated to revise any further problems with the Quick-start guide.
