### ISSUE TITLE
Colab: Include data to generate plot for the ENM calibration

### ISSUE THREAD

**Issue by luque82** [luquelab/pyCapsid#57]
It is necessary to provide the users the data regarding the calibration of the elastic network model (gamma fitting) and generate the plot, including it in the report (ENM section).

**Comment by colintravisbrown** [comment]
The necessary data should now be available in the b_factors.npz file in the latest version of pycapsid. Specifically, the dictionary key 'k' is the linear constant, and 'k_ci' is the confidence interval. The predicted and experimental b-factor values are already included.

**Comment by luque82** [comment]
The `b_factors.npz` file does not include the data that we need to plot and share.

In the report, we must provide the calibration plot, regression, and data equivalent to Figure 5b from your thesis. See attachment:
<img width="1280" alt="Figure_5b_Colin_thesis" src="https://github.com/luquelab/pyCapsid/assets/14349565/4a88a9c7-79a7-4f7b-a988-9b5548599375">

Based on your thesis caption, the key data missing is the squared fluctuations from the NMA.

I recommend including these squared fluctuations in the `b_factors.npz` file unless you consider that another file is more appropriate.

If you don't have time to generate the figure for the report, I'll work on and close this issue on Monday.

**Comment by colintravisbrown** [comment]
Plot is now included in the report
